package com.example.rasaushadhies.util

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import com.example.rasaushadhies.ui.screens.Medicine
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * PdfProtocolGenerator creates a professional Clinical Medicine Protocol
 * as a PDF document for Ayurvedic practitioners.
 */
object PdfProtocolGenerator {

    fun generateProtocol(context: Context, medicine: Medicine): File? {
        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 size in points
        val page = pdfDocument.startPage(pageInfo)
        val canvas: Canvas = page.canvas

        val paint = Paint()
        val textPaint = Paint().apply {
            color = Color.BLACK
            textSize = 12f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        }

        val titlePaint = Paint().apply {
            color = 0xFF2E7D32.toInt()
            textSize = 24f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }

        val headerPaint = Paint().apply {
            color = 0xFF1B5E20.toInt()
            textSize = 10f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.ITALIC)
        }
        
        val labelPaint = Paint().apply {
            color = Color.BLACK
            textSize = 13f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }

        var yPos = 50f

        // ── Header Branding ────────────────────────────
        canvas.drawText("RASAUSHADHI CLINICAL PROTOCOL", 40f, yPos, titlePaint)
        yPos += 20f
        canvas.drawText("Parul Institute of Ayurved & Research, Vadodara", 40f, yPos, headerPaint)
        
        yPos += 10f
        paint.color = 0xFF2E7D32.toInt()
        paint.strokeWidth = 2f
        canvas.drawLine(40f, yPos, 555f, yPos, paint)
        
        yPos += 30f

        // ── Metadata ──────────────────────────────────
        val sdf = SimpleDateFormat("dd MMM yyyy, HH:mm", Locale.getDefault())
        canvas.drawText("Date: ${sdf.format(Date())}", 40f, yPos, textPaint)
        canvas.drawText("ID: #${medicine.id}", 450f, yPos, textPaint)
        
        yPos += 40f

        // ── Medicine Identity ──────────────────────────
        canvas.drawText("Medicine Name (English):", 40f, yPos, labelPaint)
        yPos += 20f
        canvas.drawText(medicine.name, 40f, yPos, textPaint)
        
        yPos += 30f
        canvas.drawText("औषधि का नाम (Hindi):", 40f, yPos, labelPaint)
        yPos += 20f
        canvas.drawText(medicine.hindiName, 40f, yPos, textPaint)
        
        yPos += 40f

        // ── Therapeutic Section ────────────────────────
        canvas.drawText("THERAPEUTIC INDICATIONS:", 40f, yPos, labelPaint)
        yPos += 20f
        drawWrappedText(canvas, medicine.benefits, 40f, yPos, 500f, textPaint).let { yPos = it }
        
        yPos += 30f

        // ── Composition ────────────────────────────────
        canvas.drawText("COMPOSITION (घटक द्रव्य):", 40f, yPos, labelPaint)
        yPos += 20f
        drawWrappedText(canvas, medicine.ingredients, 40f, yPos, 500f, textPaint).let { yPos = it }
        
        yPos += 30f

        // ── Preparation ────────────────────────────────
        canvas.drawText("PREPARATION METHOD (निर्माण विधि):", 40f, yPos, labelPaint)
        yPos += 20f
        drawWrappedText(canvas, medicine.preparation, 40f, yPos, 500f, textPaint).let { yPos = it }
        
        yPos += 40f
        
        // ── Dosage ───────────────────────────────────
        canvas.drawText("STANDARD DOSAGE & VEHICLE:", 40f, yPos, labelPaint)
        yPos += 20f
        canvas.drawText("${medicine.dosage} | Vehicle: ${medicine.anupana}", 40f, yPos, textPaint)
        
        yPos = 780f // Move to footer area
        
        // ── Footer ───────────────────────────────────
        paint.color = Color.LTGRAY
        paint.strokeWidth = 1f
        canvas.drawLine(40f, yPos, 555f, yPos, paint)
        yPos += 20f
        
        val footerPaint = Paint().apply {
            color = Color.GRAY
            textSize = 9f
            textAlign = Paint.Align.CENTER
        }
        
        canvas.drawText("CONFIDENTIAL: For professional Ayurvedic use only. | Generated by Rasaushadhi App", 297f, yPos, footerPaint)

        pdfDocument.finishPage(page)

        // Save to cache directory
        val sanitizedName = medicine.name.replace(Regex("[^a-zA-Z0-String0-9]"), "_")
        val file = File(context.cacheDir, "Protocol_${sanitizedName}.pdf")
        return try {
            pdfDocument.writeTo(FileOutputStream(file))
            pdfDocument.close()
            file
        } catch (e: Exception) {
            pdfDocument.close()
            null
        }
    }

    private fun drawWrappedText(canvas: Canvas, text: String, x: Float, y: Float, width: Float, paint: Paint): Float {
        var yPos = y
        val words = text.split(" ")
        var line = ""
        
        for (word in words) {
            val testLine = if (line.isEmpty()) word else "$line $word"
            val textWidth = paint.measureText(testLine)
            
            if (textWidth > width) {
                canvas.drawText(line, x, yPos, paint)
                yPos += paint.textSize + 4f
                line = word
            } else {
                line = testLine
            }
        }
        canvas.drawText(line, x, yPos, paint)
        return yPos + paint.textSize + 10f
    }
}
